### ISSUE TITLE
Some improvements to requirements

### ISSUE THREAD

**Issue by MaiNorapong** [Chayapol-c/ku-polls#1]
### Requirements

> 1.&nbsp;This poll is created for KU community who wants to conduct surveys and polls.

This isn't a requirement. No need to put it here.

> 3.&nbsp;This poll provides an ability to submit a choice on poll items and view or modify one's choice.

Per the vision, the time a voter's choice can be modified is limited to before the closing date. You should include that for clarity as well.

The rest is OK. You could add more details about *who* can do what, but just this much is fine as well.

**Comment by MaiNorapong** [comment]
This is unrelated to this issue, but in README.md

> Django application for conduction a poll or survey.

"conducting" is the correct form. You need a gerund there.

**Comment by Chayapol-c** [comment]
Thank you for your comment. I'll add more details later.
